### ISSUE TITLE
이상치 제거 또는 변경 방법에 대해서 궁금합니다 

### ISSUE THREAD

**Issue by pyb9585** [2021-SMHRD-KDT-Bigdata-4/CUDH#43]
지금 제가 하고있는 이상치 처리방법은 그냥 제거 하는법밖엔 없는데 

또 다른 이상치  처리방법을 알고싶습니다

**Comment by princehd** [comment]
- 회귀 활용 설명변수 기준 이상치, 반응변수 기준 이상치 코드 실행 도움
